server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-home
              predicates:
                - Path=/
              uri: http://user-service:8080
              filters:
                - SetPath=/index.html

            - id: user-static-pages
              predicates:
                - Path=/index.html,/register.html,/dashboard.html,/favicon.ico
              uri: http://user-service:8080

            - id: user-login
              predicates:
                - Path=/login
              uri: http://user-service:8080
            - id: user-register
              predicates:
                - Path=/register
              uri: http://user-service:8080

            - id: user-service-api
              predicates:
                - Path=/user/**,/users/**
              uri: http://user-service:8080

            - id: refund-service
              predicates:
                - Path=/refund/**,/refunds/**
              uri: http://refund-service:8081

            - id: record-service
              predicates:
                - Path=/record/**,/records/**
              uri: http://record-service:8082

            - id: medical-service
              predicates:
                - Path=/medical/**,/medicine/**
              uri: http://medical-service:8083

            - id: refund-static
              predicates:
                - Path=/refund/refundApplication.html
              uri: http://refund-service:8081
              filters:
                - SetPath=/refundApplication.html

            - id: record-static
              predicates:
                - Path=/record/refundRecordQuery.html
              uri: http://record-service:8082
              filters:
                - SetPath=/refundRecordQuery.html

            - id: medical-static
              predicates:
                - Path=/medical/identityVerification.html
              uri: http://medical-service:8083
              filters:
                - SetPath=/identityVerification.html

            - id: refund-static
              predicates:
                - Path=/refund/refundApplication.html
              uri: http://refund-service:8081

            - id: refund-api
              predicates:
                - Path=/refund/**,/refunds/**
              uri: http://refund-service:8081

            - id: record-static
              predicates:
                - Path=/record/refundRecordQuery.html
              uri: http://record-service:8082
              filters:
                - SetPath=/refundRecordQuery.html

            - id: record-api
              predicates:
                - Path=/record/**,/records/**
              uri: http://record-service:8082

            - id: medical-static-identity
              predicates:
                - Path=/medical/identityVerification.html
              uri: http://medical-service:8083
              filters:
                - SetPath=/identityVerification.html

            - id: medical-static-hospital
              predicates:
                - Path=/medical/hospitalChoice.html
              uri: http://medical-service:8083
              filters:
                - SetPath=/hospitalChoice.html

            - id: medical-api
              predicates:
                - Path=/medical/**,/medicine/**
              uri: http://medical-service:8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
